# -*- coding: utf-8 -*-
"""20SW049 Lab02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vo6xnBEpZaX0LoR0JoftSr341CYK1mGg
"""

points = 14  # use this input to make your submission

# write your if statement here
if 1 <= points <= 50:
    result = "Congratulations! You won a wooden rabbit prize."
elif 51 <= points <= 150:
    result = "Congratulations! You won a no prize."
elif 151 <= points <= 180:
    result = "Congratulations! You won a water thin mint prize."
elif 181 <= points <= 200:
    result = "Congratulations! You won a penguin prize."
else:
    result = "Dear, no prize this time."

print(result)

answer = 174 # Provide the answer here
guess = 11 # Provide the guess here

if guess < answer:
    result = "Oops! Your guess was too low."
elif guess > answer:
    result = "Oops! Your guess was too high."
else:
    result = "Nice! Your guess matched the answer!"

print(result)

def calculate_tax(purchase_amount, state):
    tax_rates = {
        'CA': 0.075,
        'MN': 0.095,
        'NY': 0.089
    }

    if state in tax_rates:
        tax_rate = tax_rates[state]
        tax_amount = purchase_amount * tax_rate
        total_amount = purchase_amount + tax_amount
        return total_amount
    else:
        print("State not found in the tax rates.")
        return None

# Test the function
purchase_amount = 100
state = 'CA'
total_amount_with_tax = calculate_tax(purchase_amount, state)
print(f"Total amount with tax in {state}: ${total_amount_with_tax:.2f}")

my_list = ["the","fast", "blue" , "car", "jumped","over", "the" , "big" , "rock"]

for element in my_list:
    print(element)

Multiple=[x for x in range (1, 31) if x%5==0]
print(Multiple)

names = ["Fajar", "Kainat", "Shohaira", "Ayesha", "Zukhrufa"]
# Using list comprehension to extract first names in lowercase
first_names = [name.split()[0].lower() for name in names]

print(first_names)

Square = [x for x in range(3,21) if x%3==0]
print(Square)

scores = {
    "Rick Sanchez": 70,
    "Morty Smith": 35,
    "Summer Smith": 82,
    "Jerry Smith": 23,
    "Beth Smith": 98
}

passed = [x for x in scores if scores[x] >= 65]
print(passed)

cast_names = ["Barney", "Robin", "Ted", "Lily", "Marshall"]
cast_heights = [72, 68, 72, 66, 76]

cast = dict(zip(cast_names, cast_heights))
print(cast)

cast = ["Barney Stinson", "Robin Scherbatsky", "Ted Mosby", "Lily Aldrin", "Marshall Eriksen"]
heights = [72, 68, 72, 66, 76]

for i, x in enumerate(cast):
    cast[i] = x + " " + str(heights[i])

print(cast)